apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: employee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 024848473432.dkr.ecr.ap-south-1.amazonaws.com/employee-management-backend:latest
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: postgres.employee-app.svc.cluster.local
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
 
        - name: DB_PORT
          value: "5432"
        - name: ALLOWED_ORIGINS
          value: "*"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: employee-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend
  type: ClusterIP

