apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: employee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: frontend
        image: 024848473432.dkr.ecr.ap-south-1.amazonaws.com/employee-management-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: APP_API_URL 
          value: http://backend:8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: employee-app
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 3000
  selector:
    app: frontend
  type: NodePort

